var questionBank = [];

questionBank.push(problem111());
questionBank.push(problem112());
questionBank.push(problem113());
questionBank.push(problem114());
questionBank.push(problem115());
questionBank.push(problem116());
questionBank.push(problem117());
questionBank.push(problem118());
questionBank.push(problem119());
questionBank.push(problem1110());
questionBank.push(problem1111());
questionBank.push(problem1112());
questionBank.push(problem1113());
questionBank.push(problem1114());
questionBank.push(problem1115());
questionBank.push(problem1116());
questionBank.push(problem1117());
questionBank.push(problem1118());
questionBank.push(problem1119());
questionBank.push(problem1120());
console.log(questionBank);